version: 2.1

executors:
  node22:
    docker:
      - image: cimg/node:22.12.0

jobs:
  build:
    executor: node22
    steps:
      - checkout
      - run:
          name: Install Deno
          command: |
            curl -fsSL https://deno.land/x/install/install.sh | sh
            echo 'export DENO_INSTALL="$HOME/.deno"' >> $BASH_ENV
            echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Deno type check
          command: deno task check

workflows:
  version: 2.1
  build:
    jobs:
      - build
